### ISSUE TITLE
Do bestline next!

### ISSUE THREAD

**Issue by elimisteve** [edam/vlang-greadline#1]
Thank you for creating this!

It would be sick if next you did the same thing but for bestline, which IMO has the traits we all want: https://github.com/jart/bestline

I've considered doing this myself then integrating bestline into V's currently-minimal REPL (with almost no keyboard shortcuts -- something else bestline also fixes!), but I haven't had the time.

**Comment by edam** [comment]
Hi. Thanks for suggestion. I will consider it. I want to do a couple of other libraries first though. :)
